(function(){'use strict';
const C=window.ADCalendar,$=s=>document.querySelector(s),num=n=>n.toLocaleString('en-GB');
function error(message){$('#form-error').textContent=message;$('#form-error').hidden=false;$('#result').classList.remove('show');$('#result').hidden=true;}
function show(html){$('#form-error').hidden=true;$('#result').hidden=false;$('#result').innerHTML=html;$('#result').classList.add('show');}
function columns(a){return `<div class="age-columns">${[[a.y,'years'],[a.m,'months'],[a.d,'days']].map(([v,u])=>`<div><b>${v}</b><span>${v===1?u.slice(0,-1):u}</span></div>`).join('')}</div>`;}
function weekday(d,short=false){return C.fmt(d,{weekday:short?'short':'long',day:undefined,month:undefined,year:undefined});}
function ageResult(d,t,example=false){const a=C.age(d,t),dd=C.days(d,t),next=C.nextBirthday(d,t),left=C.days(t,next),previous=C.anniversary(d,next.getUTCFullYear()-1),progress=left===0?100:Math.max(0,Math.min(100,100*C.days(previous,t)/C.days(previous,next)));return `<div class="result-layout"><div class="age-summary"><div class="result-heading">YOUR TIME, SO FAR <span class="result-badge">${example?'Example result':'Your result'}</span></div>${columns(a)}<div class="age-facts"><span><b>${num(dd)}</b> days lived</span><span>Born on a <b>${weekday(d)}</b></span></div></div><div class="birthday-panel"><div class="birthday-ring" style="--progress:${progress}%" aria-label="${left} days until your birthday"><div><b>${left}</b><span>days to go</span></div></div><div class="birthday-copy"><svg class="cake-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M3 21h18M5 21V12h14v9M5 16q2 3 4 0q3 3 6 0q2 3 4 0M8 12V7m4 5V7m4 5V7M8 4V2m4 2V2m4 2V2"/></svg><h3>Your next birthday</h3><p>${C.fmt(next,{weekday:'long'})}</p><p>${left===0?'Happy birthday!':'A new chapter: '+(next.getUTCFullYear()-d.getUTCFullYear())+'.'}</p></div></div></div>`;}
function calc(){const tool=document.body.dataset.tool||'home';const d=C.parse($('#dob')?.value),t=C.parse($('#asof')?.value||$('#target')?.value||C.iso(C.today()));const resultDate=x=>{if(!C.inRange(x)){error('The result must be between years 0001 and 9999.');return false;}return true;};
if(['home','age-specific','future-age','days-alive','weeks','birthday','weekday','difference','milestones','10000'].includes(tool)&&!d)return error('Please enter a valid date of birth.');
if(['home','age-specific','future-age','days-alive','weeks','birthday'].includes(tool)&&(!t||d>t))return error('The calculation date must be on or after the date of birth.');
if(tool==='home'){if(!resultDate(C.nextBirthday(d,t)))return;show(ageResult(d,t));const note=$('.calc-method');if(note)note.textContent=`Born ${C.fmt(d)}. Calculated as of ${C.fmt(t)}.`;return;}
if(tool==='age-specific'||tool==='future-age')return show(columns(C.age(d,t))+`<p class="note">Age on ${C.fmt(t)}.</p>`);
if(tool==='days-alive'||tool==='weeks'){const dd=C.days(d,t),ww=Math.floor(dd/7);return show(`<div class="big">${tool==='weeks'?num(ww)+' complete weeks':num(dd)+' days'}</div><div class="stats"><div class="stat"><b>${num(dd)}</b><span>total calendar days</span></div><div class="stat"><b>${num(ww)}</b><span>complete weeks + ${dd%7} days</span></div></div>`);}
if(tool==='birthday'){const next=C.nextBirthday(d,t);if(!resultDate(next))return;return show(`<div class="big">${C.days(t,next)} days to go</div><p>Your next birthday is <b>${C.fmt(next)}</b>. You will turn <b>${next.getUTCFullYear()-d.getUTCFullYear()}</b>.</p>`);}
if(tool==='weekday')return show(`<div class="big">${weekday(d)}</div><p>${C.fmt(d)}</p>`);
if(tool==='difference'){const b=C.parse($('#dob2').value);if(!b)return error('Please enter both birth dates.');const x=d<b?d:b,y=d<b?b:d;return show(columns(C.age(x,y))+`<p>${num(C.days(x,y))} total days apart.</p>`);}
if(tool==='milestones'){const ages=[18,21,30,40,50,60,70,80,90,100];if(!resultDate(C.addMonths(d,1200)))return;return show(`<table class="milestones"><thead><tr><th>Age</th><th>Date</th><th>Weekday</th></tr></thead><tbody>${ages.map(n=>{const x=C.addMonths(d,n*12);return `<tr><td>${n}</td><td>${C.fmt(x)}</td><td>${weekday(x,true)}</td></tr>`;}).join('')}</tbody></table>`);}
if(tool==='10000'){const x=C.addDays(d,10000);if(resultDate(x))show(`<div class="big">${C.fmt(x)}</div><p>Your 10,000th day since birth.</p>`);return;}
if(tool==='date'){const a=C.parse($('#start').value),n=Number($('#amount').value),u=$('#unit').value,sign=$('#direction').value==='add'?1:-1;if(!a||$('#amount').value===''||!Number.isSafeInteger(n)||n<0)return error('Enter a valid date and a non-negative whole number.');const x=u==='days'||u==='weeks'?C.addDays(a,n*sign*(u==='weeks'?7:1)):C.addMonths(a,n*sign*(u==='years'?12:1));if(resultDate(x))show(`<div class="big">${C.fmt(x)}</div><p>${sign>0?'Added':'Subtracted'} ${num(n)} ${u} ${sign>0?'to':'from'} ${C.fmt(a)}.</p>`);return;}
if(tool==='between'){const a=C.parse($('#start').value),b=C.parse($('#end').value);if(!a||!b)return error('Please enter both dates.');const inclusive=$('#inclusive').checked,dd=Math.abs(C.days(a,b))+(inclusive?1:0);return show(`<div class="big">${num(dd)} days</div><p>${Math.floor(dd/7)} complete weeks and ${dd%7} days.</p><p class="note">${inclusive?'Both start and end dates included.':'Elapsed calendar days; same-day dates have a difference of zero.'} Weekends and holidays are included.</p>`);}
}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('#asof,#target').forEach(i=>i.value=C.iso(C.today()));const f=$('#calculator-form');if(f)f.addEventListener('submit',e=>{e.preventDefault();calc();});if(document.body.dataset.tool==='home'){$('#result').innerHTML=ageResult(C.parse('1990-05-18'),C.parse('2026-09-19'),true);}});
})();
