(function(){'use strict';
const $=s=>document.querySelector(s);
const pad=n=>String(n).padStart(2,'0');
function isoToday(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parse(v){if(!v)return null;const [y,m,d]=v.split('-').map(Number);const x=new Date(y,m-1,d);return x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d?x:null}
function utcDay(d){return Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())}
function days(a,b){return Math.round((utcDay(b)-utcDay(a))/86400000)}
function fmt(d){return d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}
function age(a,b){if(!a||!b||b<a)return null;let y=b.getFullYear()-a.getFullYear();let m=b.getMonth()-a.getMonth();let d=b.getDate()-a.getDate();if(d<0){m--;d+=new Date(b.getFullYear(),b.getMonth(),0).getDate()}if(m<0){y--;m+=12}return{y,m,d}}
function nextBirthday(dob,from){let y=from.getFullYear();let m=dob.getMonth(),day=dob.getDate();let candidate=new Date(y,m,day);if(candidate<new Date(y,from.getMonth(),from.getDate()))candidate=new Date(y+1,m,day);return candidate}
function show(el,html){el.innerHTML=html;el.classList.add('show')}
function validPast(d){const n=parse(isoToday());return d&&d<=n}
function addMonths(d,n){const day=d.getDate();const x=new Date(d.getFullYear(),d.getMonth()+n,1);const last=new Date(x.getFullYear(),x.getMonth()+1,0).getDate();x.setDate(Math.min(day,last));return x}
function addYears(d,n){return addMonths(d,n*12)}

document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('input[type=date]').forEach(i=>{if(i.id==='asof'||i.id==='target')i.value=isoToday()});
 const home=$('#calculate');
 if(home)home.onclick=()=>{const dob=parse($('#dob').value),as=parse($('#asof').value||isoToday());if(!dob||!as){alert('Please enter valid dates.');return}if(dob>as){alert('The date of birth must be on or before the calculation date.');return}const a=age(dob,as),dd=days(dob,as),nb=nextBirthday(dob,as),to=days(as,nb);show($('#result'),`<div class="result-main"><div class="big">${a.y} years, ${a.m} months, ${a.d} days</div><div class="stats"><div class="stat"><b>${dd.toLocaleString()}</b><span>days old</span></div><div class="stat"><b>${Math.floor(dd/7).toLocaleString()}</b><span>complete weeks</span></div><div class="stat"><b>${fmt(nb)}</b><span>next birthday (${to} days)</span></div></div><p class="note">Born on ${dob.toLocaleDateString('en-US',{weekday:'long'})}. Calculated locally in your browser.</p></div>`)};
 const tool=document.body.dataset.tool;
 if(tool==='age-specific'||tool==='future-age'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#dob').value),t=parse($('#target').value);if(!d||!t){alert('Enter both dates.');return}const a=age(d,t);if(!a){alert('The target date must be on or after the birth date.');return}show($('#result'),`<div class="big">${a.y} years, ${a.m} months, ${a.d} days</div><p>On ${fmt(t)}, the age is ${a.y} years, ${a.m} months and ${a.d} days.</p>`)}}
 if(tool==='days-alive'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#dob').value),t=parse($('#target').value||isoToday());if(!d||!t||d>t){alert('Enter a valid birth date and calculation date.');return}const dd=days(d,t);show($('#result'),`<div class="big">${dd.toLocaleString()} days</div><div class="stats"><div class="stat"><b>${Math.floor(dd/7).toLocaleString()}</b><span>complete weeks</span></div><div class="stat"><b>${(dd*24).toLocaleString()}</b><span>hours</span></div><div class="stat"><b>${(dd*1440).toLocaleString()}</b><span>minutes</span></div></div>`)}}
 if(tool==='birthday'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#dob').value),t=parse($('#target').value||isoToday());if(!d||!t){alert('Enter valid dates.');return}const nb=nextBirthday(d,t);const left=days(t,nb);const turning=age(d,nb).y;show($('#result'),`<div class="big">${left} days</div><p>Your next birthday is <b>${fmt(nb)}</b>. You will turn <b>${turning}</b>.</p>`)}}
 if(tool==='weekday'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#dob').value);if(!d){alert('Enter a valid date.');return}const day=d.toLocaleDateString('en-US',{weekday:'long'});show($('#result'),`<div class="big">${day}</div><p>${fmt(d)} was a ${day}.</p>`)}}
 if(tool==='difference'){const btn=$('#calc');if(btn)btn.onclick=()=>{const a=parse($('#dob').value),b=parse($('#dob2').value);if(!a||!b){alert('Enter both dates.');return}const x=a<b?a:b,y=a<b?b:a,p=age(x,y),dd=days(x,y);show($('#result'),`<div class="big">${p.y} years, ${p.m} months, ${p.d} days</div><p>${dd.toLocaleString()} total days apart.</p>`)}}
 if(tool==='milestones'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#dob').value);if(!d){alert('Enter a valid date.');return}const ages=[18,21,30,40,50,60,70,80,90,100];let rows=ages.map(n=>{const x=addYears(d,n);return `<tr><td>${n}</td><td>${fmt(x)}</td><td>${x.toLocaleDateString('en-US',{weekday:'long'})}</td></tr>`}).join('');const t=new Date(utcDay(d)+10000*86400000);show($('#result'),`<table class="milestones"><thead><tr><th>Age</th><th>Date</th><th>Day</th></tr></thead><tbody>${rows}</tbody></table><p><b>10,000 days old:</b> ${fmt(t)}</p>`)}}
 if(tool==='10000'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#dob').value);if(!d){alert('Enter a valid date.');return}const t=new Date(utcDay(d)+10000*86400000);show($('#result'),`<div class="big">${fmt(t)}</div><p>You reach 10,000 days old on ${fmt(t)}.</p>`)}}
 if(tool==='date'){const btn=$('#calc');if(btn)btn.onclick=()=>{const d=parse($('#start').value),n=Number($('#amount').value),u=$('#unit').value,dir=$('#direction').value==='add'?1:-1;if(!d||!Number.isInteger(n)){alert('Enter a valid date and whole number.');return}let t;if(u==='days')t=new Date(utcDay(d)+dir*n*86400000);else if(u==='weeks')t=new Date(utcDay(d)+dir*n*7*86400000);else if(u==='months')t=addMonths(d,dir*n);else t=addYears(d,dir*n);show($('#result'),`<div class="big">${fmt(t)}</div><p>${dir>0?'Added':'Subtracted'} ${n.toLocaleString()} ${u} ${dir>0?'to':'from'} ${fmt(d)}.</p>`)}}
 if(tool==='between'){const btn=$('#calc');if(btn)btn.onclick=()=>{const a=parse($('#start').value),b=parse($('#end').value);if(!a||!b){alert('Enter both dates.');return}const dd=Math.abs(days(a,b));show($('#result'),`<div class="big">${dd.toLocaleString()} days</div><p>That is ${(dd/7).toFixed(2)} weeks.</p>`)}}
});
})();
