"""Build the four approved P0 pages. Content is static HTML; calculators run locally."""
from pathlib import Path
import html,json,re
ROOT=Path(__file__).resolve().parent
BASE='https://ageanddates.com'
groups={
 'age':[('en','/','English'),('id','/id/kalkulator-umur/','Bahasa Indonesia'),('de','/de/altersrechner/','Deutsch')],
 'between':[('en','/days-between-dates.html','English'),('id','/id/kalkulator-selisih-tanggal/','Bahasa Indonesia')],
 'date':[('en','/date-calculator.html','English'),('pt-BR','/pt-br/somar-dias-a-uma-data/','Português (Brasil)')]
}
pages=[
 dict(lang='id',tool='age',url='/id/kalkulator-umur/',title='Kalkulator Umur — Hitung Usia dari Tanggal Lahir',h1='Kalkulator Umur dan Usia',description='Hitung umur tepat dalam tahun, bulan, dan hari dari tanggal lahir. Lihat total hari, minggu, dan ulang tahun berikutnya.',lead='Hitung usia dari tanggal lahir hingga hari ini atau tanggal pilihan Anda.',start='Tanggal lahir',end='Hitung sampai',submit='Hitung umur',
 how='Cara menggunakan kalkulator umur',steps='Masukkan tanggal lahir, lalu pilih tanggal perhitungan. Kolom “Hitung sampai” diisi dengan tanggal hari ini dan dapat diubah. Tekan “Hitung umur” untuk melihat usia dalam tahun, bulan, dan hari, total hari, minggu penuh, bulan penuh, serta ulang tahun berikutnya.',
 rules='Cara menghitung umur dan tahun kabisat',rule='Kami menghitung bulan kalender penuh sejak tanggal lahir, lalu sisa harinya. Dua belas bulan menjadi satu tahun. Jika tanggal yang sama tidak ada pada bulan tujuan, tanggal disesuaikan ke hari terakhir bulan tersebut. Dalam kalkulator ini, ulang tahun 29 Februari jatuh pada 28 Februari pada tahun nonkabisat. Total minggu adalah jumlah hari dibagi tujuh dan dibulatkan ke bawah. Perhitungan berdasarkan tanggal kalender, sehingga perubahan zona waktu atau waktu musim panas tidak menambah atau mengurangi satu hari.',
 examples_title='Contoh perhitungan usia',examples=['Lahir 18 Mei 1990, dihitung sampai 19 September 2026: 36 tahun, 4 bulan, 1 hari; total 13.273 hari.','Lahir 29 Februari 2000, dihitung sampai 28 Februari 2025: 25 tahun menurut aturan kalkulator ini.','Lahir 31 Januari 2023, dihitung sampai 1 Maret 2023: 1 bulan dan 1 hari.'],
 context='Untuk formulir atau catatan pribadi, gunakan tanggal acuan yang diminta. Hasil ini bukan penetapan usia menurut hukum atau syarat resmi suatu lembaga.',
 faq=[('Bagaimana menghitung umur dari tanggal lahir?','Pilih tanggal lahir dan tanggal acuan. Kalkulator membagi selisih kalender menjadi tahun, bulan, dan hari; hasilnya tidak sekadar membagi jumlah hari dengan 365.'),('Apa beda umur dan usia?','Dalam penggunaan sehari-hari keduanya dapat merujuk pada lama waktu sejak lahir. Kalkulator umur dan kalkulator usia di halaman ini adalah alat yang sama.'),('Bagaimana jika lahir 29 Februari?','Pada tahun nonkabisat, alat ini menggunakan 28 Februari sebagai tanggal ulang tahun. Ketentuan administrasi atau hukum dapat menggunakan aturan berbeda.'),('Bisakah menghitung umur pada tanggal tertentu?','Bisa. Ubah “Hitung sampai” untuk memilih tanggal masa lalu atau masa depan yang tidak mendahului tanggal lahir.'),('Apakah tanggal lahir disimpan?','Kode kalkulator memproses tanggal di browser tanpa mengunggahnya, menyimpannya di penyimpanan browser, atau menaruhnya di URL. Jika Anda menyalin hasil, data tersebut masuk ke papan klip perangkat.')]),
 dict(lang='id',tool='between',url='/id/kalkulator-selisih-tanggal/',title='Kalkulator Selisih Tanggal dan Jumlah Hari',h1='Kalkulator Selisih Tanggal',description='Hitung jumlah hari antara dua tanggal, lengkap dengan minggu serta selisih tahun, bulan, dan hari. Atur tanggal awal dan akhir.',lead='Cari jumlah hari antara dua tanggal dan pilih apakah kedua tanggal ikut dihitung.',start='Tanggal awal',end='Tanggal akhir',submit='Hitung selisih tanggal',
 how='Cara menghitung selisih tanggal',steps='Isi tanggal awal dan tanggal akhir. Secara default, hasil adalah selisih hari berlalu: tanggal yang sama menghasilkan nol. Aktifkan “Hitung kedua tanggal” untuk menghitung kedua tanggal sebagai bagian dari rentang. Jika tanggal dimasukkan terbalik, hasil tetap positif dan urutannya dijelaskan.',
 rules='Hari kalender, hari kerja, dan aturan inklusif',rule='Alat ini menghitung hari kalender, termasuk Sabtu, Minggu, dan hari libur. Alat ini tidak menghitung hari kerja. Pilihan inklusif menambahkan satu hari ke selisih hari berlalu; rentang satu tanggal menjadi satu hari. Rincian tahun, bulan, dan hari tetap menunjukkan selisih kalender asli, tanpa tambahan inklusif. Bulan dihitung penuh dengan penyesuaian ke hari terakhir jika tanggal yang sama tidak tersedia. Tahun kabisat mengikuti kalender Gregorian. Perhitungan tanggal dinormalisasi ke UTC agar perubahan waktu musim panas tidak mengubah jumlah hari.',
 examples_title='Contoh jumlah hari antara dua tanggal',examples=['1 September 2026 hingga 19 September 2026: 18 hari, atau 2 minggu dan 4 hari. Jika kedua tanggal dihitung: 19 hari.','Tanggal awal dan akhir sama-sama 5 Oktober 2026: 0 hari secara default, atau 1 hari dengan pilihan inklusif.','28 Februari 2024 hingga 1 Maret 2024: 2 hari karena 2024 adalah tahun kabisat.'],
 context='Gunakan untuk merencanakan perjalanan, mencatat durasi kegiatan, atau membandingkan tanggal. Untuk tenggat resmi, periksa aturan penghitungan yang berlaku.',
 faq=[('Apakah tanggal awal ikut dihitung?','Secara default yang ditampilkan adalah selisih hari berlalu. Untuk memasukkan kedua tanggal ke dalam hitungan, aktifkan pilihan inklusif; hasil bertambah satu hari.'),('Bagaimana jika tanggal dibalik?','Kalkulator mengurutkan tanggal untuk menghitung besar selisih dan menampilkan nilai positif. Pesan pada hasil menjelaskan bahwa tanggal awal lebih akhir.'),('Apa beda hari kalender dan hari kerja?','Hari kalender mencakup semua hari. Hari kerja bergantung pada jadwal kerja dan hari libur setempat. Halaman ini hanya menghitung hari kalender.'),('Apakah tahun kabisat dihitung?','Ya. Tanggal 29 Februari ikut dihitung apabila berada dalam rentang tahun kabisat.'),('Mengapa jumlah bulan tidak sama dengan jumlah hari dibagi 30?','Panjang bulan berbeda-beda. Rincian kalender memakai bulan penuh dan sisa hari, bukan asumsi bahwa semua bulan memiliki 30 hari.')]),
 dict(lang='pt-BR',tool='date',url='/pt-br/somar-dias-a-uma-data/',title='Somar ou Subtrair Dias de uma Data — Calculadora',h1='Somar Dias a uma Data',description='Some ou subtraia dias, semanas, meses ou anos de uma data e veja a data final e o dia da semana instantaneamente.',lead='Some ou subtraia dias corridos, semanas, meses e anos para encontrar uma nova data.',start='Data inicial',submit='Calcular data',
 how='Como somar ou subtrair dias',steps='Informe a data inicial, escolha “Somar” ou “Subtrair”, digite uma quantidade inteira e selecione a unidade. O resultado mostra a data final, o dia da semana e um resumo da operação. Para calcular a data de alguns dias atrás, basta selecionar “Subtrair”.',
 rules='Fim do mês, anos bissextos e dias corridos',rule='Um dia corresponde à próxima ou à última data do calendário; uma semana equivale a sete dias. Ao adicionar meses ou anos, mantemos o número do dia quando ele existe no mês de destino. Caso contrário, usamos o último dia desse mês. Assim, 31 de janeiro de 2025 mais um mês resulta em 28 de fevereiro de 2025. A operação é feita diretamente a partir da data inicial, não como uma sequência de acréscimos mensais. Usamos datas normalizadas em UTC para evitar diferenças causadas pelo horário de verão. Sábados, domingos e feriados entram na conta: este não é um cálculo de dias úteis.',
 examples_title='Exemplos de cálculo de datas',examples=['1 de setembro de 2026 + 30 dias = 1 de outubro de 2026, quinta-feira.','31 de janeiro de 2025 + 1 mês = 28 de fevereiro de 2025, sexta-feira.','10 de março de 2024 − 2 semanas = 25 de fevereiro de 2024, domingo.'],
 context='Use os exemplos para organizar viagens, lembretes e atividades pessoais. Prazos legais e contratuais podem ter regras próprias; este cálculo não determina esses prazos.',
 faq=[('Que data será daqui a X dias?','Mantenha a data inicial como hoje, selecione “Somar”, informe X e escolha “Dias”. O cálculo inclui fins de semana e feriados.'),('Como descobrir a data de X dias atrás?','Escolha “Subtrair” e informe a quantidade de dias. O resultado será anterior à data inicial.'),('O dia inicial entra na contagem?','Somar zero dias mantém a data inicial. Somar um dia leva ao dia seguinte. Não há acréscimo inclusivo do dia inicial.'),('O que acontece ao somar um mês a 31 de janeiro?','O resultado é o último dia de fevereiro: dia 28 ou 29, conforme o ano. Somar dois meses diretamente a 31 de janeiro resulta em 31 de março.'),('Posso somar semanas, meses e anos?','Sim. Selecione a unidade correspondente. Uma semana tem sete dias; meses e anos seguem o calendário, com ajuste quando o dia não existe no mês de destino.')]),
 dict(lang='de',tool='age',url='/de/altersrechner/',title='Altersrechner — Alter genau berechnen',h1='Altersrechner',description='Berechne dein genaues Alter in Jahren, Monaten und Tagen. Zusätzlich: gesamte Tage, Wochen und Zeit bis zum nächsten Geburtstag.',lead='Berechne dein Alter aus dem Geburtsdatum – für heute oder einen beliebigen Stichtag.',start='Geburtsdatum',end='Berechnen bis',submit='Alter berechnen',
 how='So verwendest du den Altersrechner',steps='Gib dein Geburtsdatum ein und wähle den Stichtag. „Berechnen bis“ ist mit dem heutigen Datum vorbelegt. Nach dem Berechnen siehst du dein Alter in Jahren, Monaten und Tagen, die gesamten Tage, volle Wochen und Monate sowie deinen nächsten Geburtstag.',
 rules='So berechnen wir dein genaues Alter',rule='Der Rechner zählt volle Kalendermonate ab dem Geburtsdatum und anschließend die verbleibenden Tage. Zwölf Monate ergeben ein Jahr. Fehlt der ursprüngliche Tag im Zielmonat, gilt dessen letzter Tag. Für den 29. Februar verwenden wir in Nichtschaltjahren den 28. Februar als Geburtstag. Volle Wochen ergeben sich aus den gesamten Tagen geteilt durch sieben, abgerundet. Die Datumswerte werden auf UTC normalisiert, damit eine Zeitumstellung keine zusätzlichen oder fehlenden Kalendertage verursacht.',
 examples_title='Beispiele für die Altersberechnung',examples=['Geboren am 18.05.1990, Stichtag 19.09.2026: 36 Jahre, 4 Monate und 1 Tag; insgesamt 13.273 Tage.','Geboren am 29.02.2000, Stichtag 28.02.2025: nach der Regel dieses Rechners genau 25 Jahre.','Geboren am 31.01.2023, Stichtag 01.03.2023: 1 Monat und 1 Tag.'],
 context='Der Rechner hilft bei persönlichen Übersichten und bei der Planung von Geburtstagen. Für gesetzliche Altersgrenzen oder verbindliche Fristen können andere Regeln gelten.',
 faq=[('Wie berechne ich mein genaues Alter?','Trage dein Geburtsdatum und einen Stichtag ein. Das Ergebnis basiert auf Kalendermonaten und verbleibenden Tagen, nicht auf einer pauschalen Division durch 365.'),('Wie alt bin ich an einem bestimmten Datum?','Ändere das Feld „Berechnen bis“. Ein vergangener oder zukünftiger Stichtag ist möglich, solange er nicht vor dem Geburtsdatum liegt.'),('Wie wird der 29. Februar behandelt?','In Nichtschaltjahren setzt dieser Rechner den Geburtstag auf den 28. Februar. Das ist eine Rechenkonvention und keine Aussage über rechtliche Altersgrenzen.'),('Werden meine Eingaben gespeichert?','Die Berechnung erfolgt im Browser. Der Rechner lädt die Datumsangaben nicht hoch, speichert sie nicht im Browserspeicher und ergänzt sie nicht in der URL. Beim Kopieren gelangt das Ergebnis in deine Zwischenablage.'),('Warum sind Kalendermonate und Gesamttage unterschiedlich?','Monate haben 28 bis 31 Tage. Die Kalenderangabe beschreibt volle Monate und Resttage; die Gesamttage zählen dagegen jeden einzelnen Kalendertag.')])
]
common={
 'id':dict(home='Beranda',tools='Alat lainnya',language='Bahasa',hint='Format: DD/MM/YYYY',copy='Salin hasil',faq='Pertanyaan yang sering diajukan',privacy='Privasi perhitungan',private='Tanggal diproses di perangkat ini. Kode kalkulator tidak mengunggah tanggal, menyimpannya di browser, atau menambahkannya ke URL. Halaman ini tidak memuat analitik. Server hosting tetap dapat menerima data koneksi standar saat halaman dibuka.',short='Tanggal dihitung di perangkat ini, tanpa akun.',legal='Kebijakan privasi (bahasa Inggris)',terms='Ketentuan (bahasa Inggris)',contact='Kontak (bahasa Inggris)',note='Untuk informasi umum, bukan penetapan hukum.',related='Alat terkait'),
 'de':dict(home='Startseite',tools='Weitere Rechner',language='Sprache',hint='Format: TT.MM.JJJJ',copy='Ergebnis kopieren',faq='Häufige Fragen',privacy='Datenschutz bei der Berechnung',private='Die Berechnung findet auf deinem Gerät statt. Der Rechner lädt deine Datumsangaben nicht hoch, speichert sie nicht im Browserspeicher und schreibt sie nicht in die URL. Diese Seite lädt keine Analysesoftware. Beim Seitenaufruf kann der Hosting-Server übliche Verbindungsdaten erhalten.',short='Berechnung auf deinem Gerät, ohne Konto.',legal='Datenschutzerklärung (Englisch)',terms='Nutzungsbedingungen (Englisch)',contact='Kontakt (Englisch)',note='Allgemeine Information, keine rechtliche Altersfeststellung.',related='Weitere Rechner'),
 'pt-BR':dict(home='Início',tools='Outras ferramentas',language='Idioma',hint='Formato: DD/MM/AAAA',copy='Copiar resultado',faq='Perguntas frequentes',privacy='Privacidade no cálculo',private='As datas são processadas neste dispositivo. O código da calculadora não envia as datas, não as salva no armazenamento do navegador e não as inclui na URL. Esta página não carrega ferramentas de análise. O servidor de hospedagem ainda pode receber dados usuais da conexão ao abrir a página.',short='Cálculo neste dispositivo, sem cadastro.',legal='Política de privacidade (inglês)',terms='Termos (inglês)',contact='Contato (inglês)',note='Informação geral, sem determinação de prazos legais.',related='Ferramentas relacionadas')
}
def esc(s):return html.escape(s,quote=True)
def alternates(tool):
 g=groups[tool];return '\n'.join(f'<link rel="alternate" hreflang="{lang}" href="{BASE+url}">' for lang,url,_ in g)+f'\n<link rel="alternate" hreflang="x-default" href="{BASE+g[0][1]}">'
def language_links(tool,lang,label):
 return f'<nav class="language-links" aria-label="{label}">'+''.join(f'<a href="{url}" lang="{lc}" hreflang="{lc}"'+(' aria-current="page"' if lc==lang else '')+f'>{name}</a>'for lc,url,name in groups[tool])+'</nav>'
def field(name,label,lang,today=False):
 hint=common[lang]['hint'];placeholder='TT.MM.JJJJ' if lang=='de' else ('DD/MM/AAAA' if lang=='pt-BR' else 'DD/MM/YYYY')
 return f'<label for="{name}">{label}<input id="{name}" name="{name}" type="text" inputmode="numeric" maxlength="10" placeholder="{placeholder}" aria-describedby="{name}-hint" autocomplete="off" required'+(' data-today' if today else '')+f'><span class="form-hint" id="{name}-hint">{hint}</span></label>'
for p in pages:
 lang=p['lang'];c=common[lang];tool=p['tool'];url=BASE+p['url'];home=next(x['url']for x in pages if x['lang']==lang)
 fields=field('start',p['start'],lang,tool=='date')
 if tool!='date':fields+=field('end',p['end'],lang,True)
 else:fields+='<label for="direction">Operação<select id="direction" name="direction"><option value="add">Somar</option><option value="subtract">Subtrair</option></select></label><label for="amount">Quantidade<input id="amount" name="amount" type="number" value="1" min="0" step="1" required></label><label for="unit">Unidade<select id="unit" name="unit"><option value="days">Dias</option><option value="weeks">Semanas</option><option value="months">Meses</option><option value="years">Anos</option></select></label>'
 checkbox='<label class="check-row"><input name="inclusive" type="checkbox">Hitung kedua tanggal (awal dan akhir)</label>' if tool=='between' else ''
 related=[(x['url'],x['h1'])for x in pages if x['lang']==lang and x['url']!=p['url']]
 if lang=='de':related=[('/days-between-dates.html','Tage zwischen zwei Daten (Englisch)'),('/date-calculator.html','Datum addieren oder abziehen (Englisch)')]
 if lang=='pt-BR':related=[('/days-between-dates.html','Dias entre duas datas (inglês)'),('/birthday-countdown.html','Contagem até o aniversário (inglês)')]
 schema={'@context':'https://schema.org','@graph':[{'@type':'WebApplication','name':p['h1'],'url':url,'inLanguage':lang,'description':p['description'],'applicationCategory':'UtilitiesApplication','operatingSystem':'Any','browserRequirements':'Requires JavaScript','isAccessibleForFree':True},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Age & Dates','item':BASE+'/'},{'@type':'ListItem','position':2,'name':p['h1'],'item':url}]}]}
 output=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(p['title'])}</title><meta name="description" content="{esc(p['description'])}"><link rel="canonical" href="{url}"><meta name="robots" content="index,follow">
{alternates(tool)}
<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/redesign.css"><link rel="stylesheet" href="/localized.css"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
<script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="/calendar.js" defer></script><script src="/localized.js" defer></script></head>
<body class="localized-page" data-localized="{tool}"><header class="site-header"><div class="wrap nav"><a class="brand" href="{home}"><img src="/assets/logo.svg" alt="" width="39" height="39">Age &amp; Dates<span class="brand-dot">.</span></a><nav class="navlinks" aria-label="{c['tools']}"><a href="#related">{c['tools']}</a></nav></div></header>
<main><div class="wrap">{language_links(tool,lang,c['language'])}<section class="toolhero"><h1>{p['h1']}</h1><p>{p['lead']}</p></section>
<form id="localized-form" class="card calculator toolbox" novalidate><div class="formgrid">{fields}</div>{checkbox}<button type="submit" style="margin-top:18px">{p['submit']}</button><p class="privacy-line">{c['short']}</p><p id="localized-error" class="form-error" role="alert" tabindex="-1" hidden></p></form>
<div class="calculator" style="padding:0;margin-top:20px"><div id="localized-result" class="card result" aria-live="polite" hidden></div></div><div class="copy-area"><button id="copy-result" type="button" hidden>{c['copy']}</button><p id="copy-status" class="note" role="status"></p></div>
<section class="section prose"><h2>{p['how']}</h2><p>{p['steps']}</p><h2>{p['examples_title']}</h2><ul class="example-list">{''.join('<li>'+esc(x)+'</li>'for x in p['examples'])}</ul><h2>{p['rules']}</h2><p>{p['rule']}</p><p>{p['context']}</p><div class="faq"><h2>{c['faq']}</h2>{''.join('<details><summary>'+esc(q)+'</summary><p>'+esc(a)+'</p></details>'for q,a in p['faq'])}</div><section class="local-privacy"><h2>{c['privacy']}</h2><p>{c['private']}</p><a href="/privacy.html">{c['legal']}</a></section></section>
<section class="section" id="related"><h2>{c['related']}</h2><div class="related-links">{''.join('<a href="'+u+'">'+esc(t)+'</a>'for u,t in related)}</div></section></div></main>
<footer class="footer"><div class="wrap"><div class="footerlinks"><a href="{home}">{c['home']}</a><a href="/privacy.html">{c['legal']}</a><a href="/terms.html">{c['terms']}</a><a href="/contact.html">{c['contact']}</a></div>© 2026 Age &amp; Dates. {c['note']}</div></footer></body></html>
'''
 dest=ROOT/p['url'].strip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(output)
# Reciprocal tags and visible language links on each English equivalent.
for tool,g in groups.items():
 dest=ROOT/('index.html' if g[0][1]=='/' else g[0][1].lstrip('/'));s=dest.read_text()
 s=re.sub(r'\n?<!-- P0 languages -->.*?<!-- /P0 languages -->','',s,flags=re.S)
 s=s.replace('</head>','<!-- P0 languages -->'+alternates(tool)+'<!-- /P0 languages --></head>')
 s=s.replace('</main>','<!-- P0 languages --><div class="wrap">'+language_links(tool,'en','Language')+'</div><!-- /P0 languages --></main>')
 if 'href="localized.css"' not in s:s=s.replace('</head>','<link rel="stylesheet" href="localized.css"></head>')
 dest.write_text(s)
# A homepage entry for all four P0 pages, without implying equivalent intents.
dest=ROOT/'index.html';s=dest.read_text();s=re.sub(r'<!-- P0 directory -->.*?<!-- /P0 directory -->','',s,flags=re.S)
directory='<section class="section wrap"><h2>Tools in your language</h2><div class="related-links">'+''.join(f'<a href="{p["url"]}" lang="{p["lang"]}">{p["h1"]}</a>'for p in pages)+'</div></section>'
s=s.replace('</main>','<!-- P0 directory -->'+directory+'<!-- /P0 directory --></main>');dest.write_text(s)
dest=ROOT/'sitemap.xml';s=dest.read_text()
for p in pages:
 if BASE+p['url'] not in s:s=s.replace('</urlset>',f'<url><loc>{BASE+p["url"]}</loc></url>\n</urlset>')
dest.write_text(s)
print('Built 4 P0 pages; updated 3 English equivalents and sitemap.')
